openapi: 3.0.1
info:
  title: API providing data for merkazmesira-client-application
  version: 1.0.0
  description: API providing data for merkazmesira-client-application. In this version, validation and required fields of the schemas, as well as securityDefenition and authentication are not supported.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://post-mesira-api-dev.azurewebsites.net
    description: Api for merkazmesira-client-application (dev branch) on Azure
  - url: http://localhost:7274
    description: Local development environment (for testing only)

tags:
  - name: Login
    description: "Endpoints related to user authentication and login"
  - name: KabalatSakim
    description: "Endpoints for managing Kabalat Sakim operations"
  - name: Chatima
    description: "Endpoints for handling Chatima-related operations"
  - name: DeliveryStatus
    description: provide demo data for merkazmesira 
     
  
paths:
  /users/details:
    post:
      summary: Retrieve user details
      tags: [Login]
      operationId: GetUserDetails      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDetailsRequest'
              

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /delivery/statuses:
    post:
      summary: Retrieve delivery status list
      tags: [DeliveryStatus]
      operationId: GetDeliveryStatuses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryStatusListRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryStatusListResponse'   
              
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
          
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT      
  responses:
    BadRequest:
      description: Bad request (invalid input)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized (missing or invalid authentication)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - StatusCode: 401
              ErrorDescription: "Unauthorized access"
              Details: "Authentication credentials were missing or incorrect."
              Timestamp: "2025-01-20T14:30:00Z"   
    Forbidden:
      description: Forbidden (user lacks permissions)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - StatusCode: 403
              ErrorDescription: "Access denied"
              Details: "User does not have permission to access this resource."
              Timestamp: "2025-03-21T14:30:00Z"  
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - StatusCode: 404
              ErrorDescription: "Resource not found"
              Details: "The requested endpoint '/api/v1/users/12345' does not exist."
              Timestamp: "2025-01-14T14:30:00Z"   
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            - StatusCode: 500
              ErrorDescription: "Internal Server Error"
              Details: "An unexpected condition was encountered on the server."
              Timestamp: "2025-01-11T14:30:00Z"     
  schemas:
    Error:
      type: object
      properties:
        StatusCode:
          type: integer
          example: 400
          description: The HTTP status code associated with the error (e.g., 400, 401, 403, 500).
        ErrorDescription:
          type: string
          example: "Invalid input data"
          description: A brief, user-friendly description of the error.
        Details:
          type: string
          nullable: true
          example: "Missing required fields: UserID, Barcode"
          description: Additional details for debugging, included only when relevant.
        Timestamp:
          type: string
          format: date-time
          example: "2025-01-29T14:30:00Z"
          description: The exact UTC time when the error occurred.
    InfoError:
      type: object
      properties:
        errorId:
          type: integer
          example: 100
        errorDescription:
          type: string
          example: "להמשך הפעולה לחץ על הכפתור הירוק"      
    UserDetailsRequest:
      type: object
      properties:
        userID:
          type: string
          example: "012345678"                
    User:
      type: object
      properties:
        userId:
          type: string
          example: "012345678"
        name:
          type: string
          example: "משה כהן"
        atarName:
          type: string
          example: "טסט אלף"
        atar:
          type: integer
          example: 1000
        atarType:
          type: integer
          example: 14
        userGroup:
          type: integer
          example: 16
        userGroupName:
          type: string
          example: "משתמש מרכז מסירה"
        shouldDisplayKabalaScreen:
          type: boolean
          example: true
        shouldPrintHodaot:
          type: boolean
          example: true
        infoError:
          $ref: "#/components/schemas/InfoError"
    DeliveryStatusListRequest:
      type: object
      properties:
        userId:
          type: string
          example: "012345678"
        siteNumber:
          type: string
          example: "1000"
    DeliveryStatusListResponse:
      type: object
      properties:
        userId:
          type: string
          example: "012345678"
        DeliveryStatuses:
          type: array
          items:
            type: object
            properties:
              kodPeula:
                type: number
                example: 1
              perutPeula:
                type: number
                example: 1
              teurPeula:
                type: string
                example: "נמסר לנמען"
              isDelivery:
                type: boolean  
                example: true
          example:
            - kodPeula: 3
              perutPeula: 1
              teurPeula: "נמסר לנמען"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 8
              teurPeula: "נמסר לנציג הנמען"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 2
              teurPeula: "נמסר למיופ'כ מ-18"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 3
              teurPeula: "נמסר למיופ'כ מ-16"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 7
              teurPeula: "נמסר חזרה לשולח"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 40
              teurPeula: "הדבקה על הדלת"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 41
              teurPeula: "הועבר למסירה באמצעות שליח"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 61
              teurPeula: "נמסר לשליח GETT"
              isDelivery: true
            - kodPeula: 3
              perutPeula: 42
              teurPeula: "הונח בתיבה"
              isDelivery: true
            - kodPeula: 4
              perutPeula: 108
              teurPeula: "לא נדרש"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 102
              teurPeula: "סירב לקבל"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 100
              teurPeula: "עזב"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 107
              teurPeula: "תא דואר שגוי"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 101
              teurPeula: "לא ידוע בתא דואר"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 111
              teurPeula: "בבירור"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 116
              teurPeula: "הפניה"
              isDelivery: false
            - kodPeula: 4
              perutPeula: 120
              teurPeula: "ניתוב שגוי"
              isDelivery: false
    

        
  examples:
    DeliveryStatusExamples:
      summary: Full list of delivery statuses
      value:
        - kodPeula: 3
          perutPeula: 1
          teurPeula: "נמסר לנמען"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 8
          teurPeula: "נמסר לנציג הנמען"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 2
          teurPeula: "נמסר למיופ'כ מ-18"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 3
          teurPeula: "נמסר למיופ'כ מ-16"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 7
          teurPeula: "נמסר חזרה לשולח"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 40
          teurPeula: "הדבקה על הדלת"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 41
          teurPeula: "הועבר למסירה באמצעות שליח"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 61
          teurPeula: "נמסר לשליח GETT"
          isDelivery: true
        - kodPeula: 3
          perutPeula: 42
          teurPeula: "הונח בתיבה"
          isDelivery: true
        - kodPeula: 4
          perutPeula: 108
          teurPeula: "לא נדרש"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 102
          teurPeula: "סירב לקבל"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 100
          teurPeula: "עזב"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 107
          teurPeula: "תא דואר שגוי"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 101
          teurPeula: "לא ידוע בתא דואר"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 111
          teurPeula: "בבירור"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 116
          teurPeula: "הפניה"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 120
          teurPeula: "ניתוב שגוי"
          isDelivery: false
        - kodPeula: 4
          perutPeula: 175
          teurPeula: "פגום"
          isDelivery: false         
security:
  - bearerAuth: []  